GET http://localhost:3000/

###

GET http://localhost:3000/1234

###

GET http://localhost:3000/1234/Ken

###

POST http://localhost:3000/
Content-Type: application/json

{
    "lobbyPIN": 1234554
}

###

POST http://localhost:3000/1234
Content-Type: application/json

{
    "name": "PP"
}

###

POST http://localhost:3000/1234/PP
Content-Type: application/json

{
    "name": "Boat",
    "posX": 0,
    "posY": 2,
    "size": 3,
    "rotation": false
}

###

DELETE http://localhost:3000/1234554

###

DELETE http://localhost:3000/1234/PP
