GET http://localhost:3000/

###

GET http://localhost:3000/1234

###

GET http://localhost:3000/1234/Kant

###

POST http://localhost:3000/
Content-Type: application/json

{
    "lobbyPIN": 1234
}

###

POST http://localhost:3000/1234
Content-Type: application/json

{
    "name": "Kant"
}

###

DELETE http://localhost:3000/1234554

###

DELETE http://localhost:3000/1234/PP

###

POST http://localhost:3000/1234/setup
Content-Type: application/json

{
    "name": "Kant",
    "ship": [
        {
            "name": "Freegate",
            "position": [7, 8, 9]  
        },
        {
            "name": "Submarine",
            "position": [3, 4, 5]
        }
    ]
}        

###

POST http://localhost:3000/1234/attack
Content-Type: application/json

{
    "name": "Kant",
    "position": 19
}

###

POST http://localhost:3000/1234/status
Content-Type: application/json

{
    "name": "Kant"
}

###

POST http://localhost:3000/1234/deadship
Content-Type: application/json

{
    "name": "Kant"
}
